-- CareerClaw Phase 3: Daily application summary view, indexes, and constraint update
-- Adds:
--   1. 'playwright_submit' to automation_logs.action_type CHECK constraint
--   2. Composite index on automation_logs(action_type, created_at)
--   3. Indexes on applications(application_date) and applications(status, application_date)
--   4. daily_application_summary view for dashboard analytics

-- ============================================================================
-- 1. Expand automation_logs.action_type CHECK to include 'playwright_submit'
-- ============================================================================

-- Drop the existing check constraint and recreate with expanded values.
-- The constraint name is auto-generated by PostgreSQL as "automation_logs_action_type_check".
ALTER TABLE automation_logs
    DROP CONSTRAINT IF EXISTS automation_logs_action_type_check;

ALTER TABLE automation_logs
    ADD CONSTRAINT automation_logs_action_type_check
    CHECK (action_type IN (
        'job_search', 'application_submit', 'proposal_submit',
        'email_send', 'follow_up', 'profile_update', 'calendar_sync',
        'playwright_submit'
    ));

-- ============================================================================
-- 2. New indexes for efficient date-based queries
-- ============================================================================

-- Composite index for querying automation_logs by action + date range
CREATE INDEX IF NOT EXISTS idx_automation_logs_action_created
    ON automation_logs(action_type, created_at DESC);

-- Application date index for daily summary aggregations
CREATE INDEX IF NOT EXISTS idx_applications_application_date
    ON applications(application_date);

-- Composite index for filtering by status + date (used in daily summary)
CREATE INDEX IF NOT EXISTS idx_applications_status_application_date
    ON applications(status, application_date);

-- ============================================================================
-- 3. Daily application summary view
-- ============================================================================

CREATE OR REPLACE VIEW daily_application_summary AS
SELECT
    d::date AS summary_date,
    (SELECT count(*) FROM jobs WHERE created_at::date = d::date) AS jobs_added,
    (SELECT count(*) FROM applications WHERE created_at::date = d::date) AS applications_created,
    (SELECT count(*) FROM applications WHERE application_date = d::date AND status = 'applied') AS applications_submitted,
    (SELECT count(*) FROM applications WHERE created_at::date = d::date AND notes LIKE '%Auto-submit failed%') AS submissions_failed,
    (SELECT count(*) FROM automation_logs WHERE action_type = 'playwright_submit' AND created_at::date = d::date) AS playwright_runs
FROM generate_series(
    (SELECT COALESCE(min(created_at::date), CURRENT_DATE) FROM jobs),
    CURRENT_DATE,
    '1 day'::interval
) d;
